openapi: "3.1.0"
info:
  version: 1.0.0
  title: Stock Ticker
paths:
  /livez:
    get:
      summary: Liveness probe
      operationId: livez
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        "200":
          description: Stock Ticker is healthy

  /readyz:
    get:
      summary: Readiness probe
      operationId: readyz
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        "200":
          description: Stock Ticker is ready

  /ticker:
    get:
      summary: Get stock data
      operationId: ticker
      parameters:
        - name: days
          in: query
          description: How many days to return data for
          required: false
          schema:
            type: integer
            format: int64
        - name: source
          in: query
          description: Stock code to source data from
          required: false
          schema:
            type: string

      responses:
        "200":
          description: Ticker data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TickerResponse"
        "400":
          description: "Invalid Query strings provided"
        "500":
          description: "Internal error"

components:
  schemas:
    StockTickerEntry:
      type: object
      required:
        - open_price
        - high_price
        - low_price
        - close_price
        - total_volume
        - date
      properties:
        open_price:
          description: Stock price at market open
          type: number
          minimum: 0
        high_price:
          description: Highest daily stock price before market close
          type: number
          minimum: 0
        low_price:
          description: Lowest daily stock price before market close
          type: number
          minimum: 0
        close_price:
          description: Stock price on market close
          type: number
          minimum: 0
        total_volume:
          description: Total volume for the day
          type: integer
          minimum: 0
        date:
          type: string
          format: date

    TickerResponse:
      type: object
      required:
        - average_closing_price
        - time_series_data
        - timezone
        - symbol
        - last_refreshed
      properties:
        average_closing_price:
          description: Average of all the closing prices
          type: number
          minimum: 0

        time_series_data:
          type: array
          description: Data for the given days
          items:
            $ref: "#/components/schemas/StockTickerEntry"

        timezone:
          type: string
          description: Timezone the data is presented in

        symbol:
          type: string
          description: Stock symbol data represents

        last_refreshed:
          type: string
          format: date
          description: Date the data was last refreshed
